AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to deploy a lambda which is triggered by an S3 event.

Parameters:
  DeploymentBucket:
    Type: String
    Description: Enter the name of the S3 bucket where your deployment package is.
    Default: delon9-daily-grind-lambda-zips
  DeploymentPackageKey:
    Type: String
    Description: Enter the name of the S3 key of your deployment package.
    Default: daily-grind.zip
  BucketNameRawData:
    Type: String
    Description: Enter the name of S3 bucket you wish to create.
    Default: delon9-daily-grind-raw-data

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Daily-Grind-Extract-CSV 
      Runtime: python3.10
      Handler: lambda_function.lambda_handler #YOUR-HANDLER-NAME(e.g. app.main.lambda_handler)
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 300
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentPackageKey
      VpcConfig:
        SecurityGroupIds:
          - SECURITY-GROUP-ID
        SubnetIds:
          - SUBNET-ID

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - S3BucketPermission
    Properties:
      BucketName: !Ref BucketNameRawData
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn

  S3BucketPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketNameRawData}"