version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container_group_project_dg
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container_group_project_dg
    restart: always
    ports:
      - 8080:8080
volumes: 
  my_db: