name: Github action for Final-Group((Daily-Grind)) Project 

# on: workflow_dispatchffffff
on: 
  push:
      branches:
        - main
    # paths:
    #   - Database/*

# on: pull_request:
#     # Sequence of patterns matched against refs/heads
#     branches:    
#       - main
permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      #-----------for testing (install dependecies and run the test)----------------------------------   
      - name: Install test dependencies
        run: python3 -m pip install -r requirements-test.txt

      - name: Run Unit test
        run: python3 -m pytest -v
      #-----------for lambda (install dependecies and zip up the files)-------------------------------
      - name: Install Lammbda dependecies
        run: |
          python3 -m pip install --platform manylinux2014_x86_64 \
          --target=Database --implementation cp --python-version 3.10 \
          --only-binary=:all: --upgrade -r requirements-lambda.txt
      #-----------for lambda (install dependecies, zip up the files, load the zip file to S3 (deployment/zip)bucket and )--------
      - name: Configure AWS credentials from delon9 account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-1
      - name: Package CloudFormation template
        run: aws cloudformation package --template-file ./Database/template_daily_grind.yml --s3-bucket delon9-daily-grind-lambda-zips --output-template-file stack-template-packaged.yml 
      - name: Deploy CloudFormation stack
        run: aws cloudformation deploy --stack-name delon9-daily-grind-stack --template-file stack-template-packaged.yml --region eu-west-1 --capabilities CAPABILITY_IAM